version: "3.9"
services:
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3000:3000
    user: '104'
  frontend:
    container_name: react_medica
    image: react_medica:1.0.0
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
    - '8080:8080'
  api-gateway:
    container_name: api-gateway
    image: api-gateway:1.0.0
    environment:
       - MONGO=mongodb://
    build:
        dockerfile: microservices/api-gateway/Dockerfile
        context: .
    ports:
    - '9000:9000'
  analyzer:
    container_name: analyzer
    image: analyzer:1.0.0
    build:
        dockerfile: Dockerfile
        context: ./microservices/analyzer
    ports:
    - '9020:9020'
    